### ISSUE TITLE
Use template strings to concatenate

### ISSUE THREAD

**Issue by Ryuno-Ki** [stev47/ajar#2]
Hello,

since you're diving into ECMAScript 2015 (aka ES2015 aka ECMAScript 6) anyway, you could take advantage of [template strings](https://hacks.mozilla.org/2015/05/es6-in-depth-template-strings-2/) in [your code](https://github.com/stev47/ajar/blob/9f6f44a025a0bd47f570bb362a84b414a51199a9/ajar.js#L4). For example:

``` js
qstr.push(encodeURIComponent(key) + '=' + encodeURIComponent(params[key]))
```

could be [written as](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=var%20qstr%20%3D%20[]%3B%0Avar%20params%20%3D%20{foo%3A%20%27bar%27}%0Afor%20%28key%20in%20params%29%0A%20%20%20%20qstr.push%28%60%24{encodeURIComponent%28key%29}%20%3D%20%24{encodeURIComponent%28params[key]%29}%60%29)

``` js
qstr.push(`${encodeURIComponent(key)}=${encodeURIComponent(params[key])})
```

Okay, it will make more sense if the string gets larger, but you get the idea :-)

**Comment by stev47** [comment]
Template strings are nice, but in this example I'd actually say it hurts readabiltiy.
If you like them that much anyway, just send a pull request and I merge it.
