### ISSUE TITLE
Don't export a delete method

### ISSUE THREAD

**Issue by Ryuno-Ki** [stev47/ajar#6]
If possible, I wouldn't opt for naming a method `delete` since it can be confused with JavaScript's [delete operator](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Operators/delete) (and [IE does so](http://stackoverflow.com/a/26479152)).

AngularJS has a `remove` method because of that.

Discovered while working on #5.

**Comment by stev47** [comment]
Using reserved words for property names is fine according to the spec (apparently even as of ES5). ES6 even defines `Map.prototype.delete()`. You can probably resolve this for IE by precompiling using browserify and some ES6 shim (`obj['delete']()`) should work too).
